version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file: .env
    volumes:
      - ./server:/var/www/html:delegated
    networks:
      default:
        aliases:
         - app.internal

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - ./server:/var/www/html:delegated
    ports:
      - '80:80'
    environment:
      - NGINX_PHP_FPM_HOST=app.internal
    networks:
      default:
        aliases:
         - web.internal

  database:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=linkedup
    networks:
      default:
        aliases:
         - database.internal

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./:/project:delegated

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - database
    environment:
      PMA_HOST: database 
